### ISSUE TITLE
how to add hot reloading to this?

### ISSUE THREAD

**Issue by movingelectrons** [MitchPierias/Reactron#3]
its kindof a pita to have to run 'npm run-script build' && electon .' after every file change.   do you know how i would go about adding hot reloading to this?  ty

**Comment by MitchPierias** [comment]
Let me have a look into what I've configured and push some updates. Seems like the boilerplate it outputs is now far behind what would be considered a 'standard project'

**Comment by MitchPierias** [comment]
Hot module reloading has now been added. You can now start the react development environment with
```
npm run start:react
```
and in a separate terminal
```
npm run start:electron
```
to connect with the development server with hot module reloading

**Comment by movingelectrons** [comment]
thanks!  but did you remember to push your changes?  github still shows last update was 2 months ago.

**Comment by MitchPierias** [comment]
Yes, `Reactron` or `create-react-app` pulls it's source from [React-Electron-Boilerplate](https://github.com/MitchPierias/React-Electron-Boilerplate). I haven't merged the two repositories yet... It doesn't intelligently merge on `init` though, so it might be better to copy the `webpack.config.js` and `package.json` dependencies from [React-Electron-Boilerplate](https://github.com/MitchPierias/React-Electron-Boilerplate) if your integrating with an existing project.
